# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

require:
  - rubocop-rails
  - rubocop-rspec

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 10

Style/MutableConstant:
  Enabled: false

RSpec/ImplicitExpect:
  EnforcedStyle: 'should'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*_spec.rb'

AllCops:
  NewCops: disable
  Exclude:
    - 'bin/**'
    - 'config/**/*.rb'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*.rb'
    - 'behaviour/**/*'
    - '_spec/**/*'
